version: '3.8'
services:
  dev-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: SA
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: nestjs
    networks:
      - nestjsdemo
networks:
  nestjsdemo:


